server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=product_service
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Options: validate | update | create | create-drop
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}